spring:
  # ehcahe配置
#  cache:
#    type: ehcache
#    ehcache:
#      config: classpath:ehcache.xml

  #数据源配置
  datasource:
    username: sp2p
    password: 123456
    # 注意，必须要加上useUnicode=true&characterEncoding=utf8，不然会出现中文乱码问题
    url: jdbc:mysql://localhost:3306/test2?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    #z指定数据源，不用默认的数据源
    type: com.alibaba.druid.pool.DruidDataSource

#初始化建立物理链接个数
    initiaSize: 5
#    最小连接池数量
    minIdle: 5
#    最大连接池数量
    maxActive: 20
#    销毁连接池检查时间间隔，每间隔该时间检查并销毁多余的连接
#    创建新连接数间隔时间音隔，当连接数小于最小连接数时，会自动创建相应的链接
    timeBetweenEvictionRunsMillis: 60000
#    连接保持不被销毁的最大时间，当连接的空闲时间大于该 值时，会被销毁，直到连接到到minIdle为止
    minEvictableIdleTimeMillis: 300000
#    用来检测是否失效
    validationQuery: select 1 from dual
#    申请连接时检测，如果空闲时间大于 timeBetweenEvictionRunsMillis， 执行validationQuery看连接是否有效
    testWhileIdle: true
#    申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
    testOnBorrow: false
#    归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    testOnReturn: false
#    是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
    poolPreparedStatements: true
#   配置监控拦截的filters, 去掉后监控界面sql无法统计， wall用于防火墙
    filters: stat,wall,slf4j
#   每个statement缓存大小
    maxPoolPreparedStatmentPerConnectionSize: 20
#    合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
#    监控方面配置，慢sql配置
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

#      可以执行的Sql语句
#      schema:
#        - classpath: xxx.sql

mybatis:
# 全局配置
  config-location: classpath:mybatis\mybaits-config.xml
#  单个文件配置，直接用 *.xml 将所有的 xml 全部配置进去
  mapper-locations: classpath:mybatis\mapper/*.xml

#改变访问端口号
#server:
#  port: 9000

#  spring.data.mongodb.uri=mongodb://name:pass@localhost:27017/dbname